# Docker

build:
	docker compose build
up:
	docker compose up -d
down:
	docker compose down
logs:
	docker compose logs -f
devdb:
	docker compose up flix_db -d
mongo:
	docker compose up mongo -d


# Django
test:
	python -m pytest -vvv
	coverage html
run_dev:
	python manage.py runserver


# Linter
lint:
	ruff check
fix:
	ruff check --fix
format:
	ruff format
coverage:
	coverage report
coverage-html:
	coverage html
