# Docker
network:
	docker network create flix_network
db:
	docker run --name flix_db \
	-e POSTGRES_DB=${POSTGRES_DB} \
	-e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
	-p ${POSTGRES_PORT}:${POSTGRES_PORT} \
	-v "/home/will/IT/Portfolio/flix-api/.postgres_data:/var/lib/postgresql/data" \
	--network=flix_network \
	-d postgres
web:
	docker run  --name flix_web \
	--env-file .env \
	--network=flix_network \
	-p 8000:8000 \
	flix_web:0.1
build:
	docker compose build
up:
	docker compose up -d
down:
	docker compose down
logs:
	docker compose logs -f


# Django
test:
	python -m pytest -vvv
	coverage html
run_dev:
	python manage.py runserver

# Poetry
export_plugin:
	poetry self add poetry-plugin-export
poetry-install:
	pip install poetry
poetry-requirements:
	poetry add $(cat requirements.txt)
poetry-dev-requirements:
	poetry add --group-dev $(cat requirements_dev.txt)
requirements:
	poetry export \
	--format=requirements.txt \
	--without-hashes \
	--without group_dev \
	--output=requirements.txt

	sed -i 's/ *;.*//' requirements.txt
requirements_dev:
	poetry export \
	--format=requirements.txt \
	--without-hashes \
	--only group_dev \
	--output=requirements_dev.txt

	sed -i 's/ *;.*//' requirements_dev.txt

# Linter
lint:
	ruff check
fix:
	ruff check --fix
format:
	ruff format
coverage:
	coverage report
coverage-html:
	coverage html