# Generated by Django 5.2.4 on 2025-11-14 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_remove_genre_id_genre_created_at_genre_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
