# Generated by Django 5.2.4 on 2025-11-14 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_remove_actor_id_actor_created_at_actor_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
