from django.db.models import Avg
from rest_framework import serializers

from apps.actors.serializers import ActorSerializer
from apps.genres.serializers import GenreSerializer
from apps.movies.models import Movie


class MovieModelSerializer(serializers.ModelSerializer):
    LIMIT_RESUME_CHARACTERS = 500
    LIMIT_YEAR_OF_BIRTH = 1900

    ai_description = serializers.BooleanField(
        required=False,
        default=False,
        read_only=True,
        help_text='If True, the description will be generated by the AI.',
    )

    class Meta:
        model = Movie
        fields = '__all__'

    def validate_release_date(self, value):
        if value.year < self.LIMIT_YEAR_OF_BIRTH:
            raise serializers.ValidationError(f'The release date can not be less than {self.LIMIT_YEAR_OF_BIRTH}.')

        return value

    def validate_resume(self, value):
        if len(value) > self.LIMIT_RESUME_CHARACTERS:
            raise serializers.ValidationError(f'The resume can not have lenght more than {self.LIMIT_RESUME_CHARACTERS} characters')

        return value


class MovieListDetailSerializer(serializers.ModelSerializer):
    actors = ActorSerializer(many=True)
    genre = GenreSerializer()
    rate = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = Movie
        fields = [
            'uuid',
            'title',
            'genre',
            'actors',
            'release_date',
            'rate',
            'resume',
        ]

    def get_rate(self, obj):
        rate = obj.reviews.aggregate(Avg('stars'))['stars__avg']
        if rate:
            return round(rate, 1)
        return None


class MovieStatsSerializer(serializers.Serializer):
    total_movies = serializers.IntegerField()
    movies_by_genre = serializers.ListField()
    total_reviews = serializers.IntegerField()
    average_stars = serializers.FloatField()


class MovieDescriptionSerializer(serializers.Serializer):
    movie_uuid = serializers.PrimaryKeyRelatedField(queryset=Movie.objects.all())
