name: Docker Image Release
on: [workflow_call]

jobs:
  docker-image-release:
    name: Docker Image Release
    runs-on: ubuntu-latest
    environment: DOCKERHUB_CREDENTIALS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login@action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Tag Name
        id: Tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: make build TAG=${{ steps.tag.outputs.tag }}

