name: Quality Assurance - Makefile
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  [push]
jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11-alpine
    environment: FLIX_API_DEVELOPMENT
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: $PG_NAME
          POSTGRES_PASSWORD: $PG_PASSWORD
          POSTGRES_USER: $PG_USER

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v4

      - name: Upgrade PIP
        run: pip install --upgrade pip

      - name: Install Poetry
        run: pip install poetry

      - name: Init Poetry
        run: poetry init --no-env

      - name: Install Requirements
        run: make poetry-equirements

      - name: Install Dev Requirements
        run: make poetry-dev-requirements

      - name: Lint
        run: make lint

      - name: Tests
        run: make test

