# .github/workflows/ci-compose.yml
name: CI com Docker Compose

on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: FLIX_API_DEVELOPMENT
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Generate .env File
        run: |
          echo "PG_NAME=${{ secrets.PG_NAME }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          cat .env

      - name: Build e sobe containers
        run: |
          docker compose up -d --build

      - name: Verificar estado dos serviços
        run: |
          docker ps -a
          echo "------"
          docker compose config
          echo "-------"
          docker logs flix-api-flix_db-1

      - name: Verificar estado do Projeto
        run: |
          docker exec flix-api-flix_web-1 python manage.py check

      - name: Rodar migrações
        run: docker compose exec flix-api-flix_web-1 python manage.py migrate --no-input

      - name: Rodar testes
        run: docker compose exec flix-api-flix_web-1 python manage.py test --verbosity=2

      - name: Derrubar containers
        run: docker compose down -v
