name: learn-github-actions-with-django
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: FLIX_API_DEVELOPMENT
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade PIP
        run: pip install --upgrade pip

      - name: Create Container network
        run: docker network create flix_network

      - name: Start DB Service
        run: |
          docker run --name ${PG_NAME} \
          -e POSTGRES_DB=${PG_NAME} \
          -e POSTGRES_PASSWORD=${PG_PASSWORD} \
          -p ${PG_PORT}:${PG_PORT} \
          --network=flix_network \
          -d postgres

      - name: Build Web Service
        run: docker build --tag flix_web:0.1 .

      - name: Start Web Service
        run: |
          docker run --name flix_web \
          --network=flix_network \
          -e PG_NAME=$PG_NAME \
          -e PG_USER=$PG_USER \
          -e PG_PASSWORD=$PG_PASSWORD \
          -e PG_HOST=$PG_HOST \
          -e PG_PORT=$PG_PORT \
          -e DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
          -p 8000:8000 \
          -d flix_web:0.1

      - name: Check Web Service
        run: |
          docker exec flix_web python manage.py check

      - name: Run Django Tests
        run: |
          docker exec flix_web python manage.py test --verbosity=2

      - name: Tear down
        run: |
          docker container stop flix_web || true
          docker container stop flix_db || true
          docker container prune -f



