name: Quality Assurance - Makefile and Docker Compose in Push
run-name: Pushing branch ${{ github.branch }} into ${{ github.repository}} by ${{ github.actor }}
on:
  [push]
jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    environment: FLIX_API_DEVELOPMENT

    env:
      POSTGRES_DB: ${{ secrets.PG_NAME }}
      POSTGRES_USER: ${{ secrets.PG_USER }}
      POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.PG_HOST }}
      POSTGRES_PORT: ${{ secrets.PG_PORT }}
      DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: .env configuration with secrets
        run: |
          env | grep POSTGRES_

      - name: Build and Start containers with Makefile
        run: |
          make build
          make up

      - name: Check Services
        run: |
          docker ps -a
          docker compose logs

      - name: Test Running
        run: make test

      - name: Tear down
        if: always()
        run: make down
