name: Quality Assurance - Makefile and Docker Compose in Push
run-name: Pushing branch ${{ github.branch }} into ${{ github.repository}} by ${{ github.actor }}
on:
  [push, workflow_call]
jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    environment: FLIX_API_DEVELOPMENT

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: .env configuration with secrets
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.PG_NAME }}" >> .env
          echo "POSTGRES_USER=${{ secrets.PG_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.PG_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.PG_PORT }}" >> .env

      - name: Build and Start containers with Makefile
        run: |
          make -f Makefile.dev build
          make -f Makefile.dev up

      - name: Check Services
        run: |
          docker ps -a
          docker compose logs flix_web

      - name: PEP8 Analysis
        run: make -f Makefile.dev lint

      - name: Test Running
        run: make -f Makefile.dev test

      - name: Tear down
        if: always()
        run: make down
