name: Quality Assurance - Makefile and Docker Compose in Push
run-name: Pushing branch ${{ github.branch }} into ${{ github.repository}} by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    environment: FLIX_API_DEVELOPMENT

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.PG_NAME }}
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_DB: ${{ secrets.PG_NAME }}
      POSTGRES_USER: ${{ secrets.PG_USER }}
      POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: PEP8 Analysis
        run: flake8 . --count

      - name: Django Tests
        run: python manage.py test --verbosity=2

